### ISSUE TITLE
Headless exception problems

### ISSUE THREAD

**Issue by captaindannduece** [baldapps/airtaskdesktop#2]
user@computer:~ $ sudo java -jar airtaskdesktop.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.balda.airtask.AirTask.main(AirTask.java:164)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:307)
        at com.balda.airtask.ClipboardListener.<init>(ClipboardListener.java:37)
        at com.balda.airtask.ClipboardListener.<clinit>(ClipboardListener.java:40)
        ... 1 more
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:174)
        at com.balda.airtask.ui.SendMessage.<init>(SendMessage.java:88)
        at com.balda.airtask.AirTask$1.run(AirTask.java:160)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by baldapps** [comment]
AirTask requires an X server. If you don't have a graphic environment you can only use the program from command line.

**Comment by captaindannduece** [comment]
Thats what I am doing.

**Comment by captaindannduece** [comment]
Its returning this from ssh.

**Comment by baldapps** [comment]
If you are running the program in ssh, you need to configure X server and then use ssh -X to have the X forwarding. When I said "use from command line" I mean using the command line options. You can see a list with "-h" option. If you start the program without any option, it will try to start the graphic.
